/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtnCont: typeof import('./src/components/container/BtnCont.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardCont: typeof import('./src/components/container/CardCont.vue')['default']
    CatchRateCalc: typeof import('./src/components/calculators/CatchRateCalc.vue')['default']
    FeatureGrid: typeof import('./src/components/wiki/FeatureGrid.vue')['default']
    FMoveCalc: typeof import('./src/components/calculators/FMoveCalc.vue')['default']
    FPokeCalc: typeof import('./src/components/calculators/FPokeCalc.vue')['default']
    HomeHeader: typeof import('./src/components/sections/HomeHeader.vue')['default']
    ListComponent: typeof import('./src/components/ListComponent.vue')['default']
    MasterNav: typeof import('./src/components/nav/MasterNav.vue')['default']
    MoveCostCalc: typeof import('./src/components/calculators/MoveCostCalc.vue')['default']
    NecrozParallaxBG: typeof import('./src/components/backgrounds/NecrozParallaxBG.vue')['default']
    ParallaxBg: typeof import('./src/components/backgrounds/ParallaxBg.vue')['default']
    PermitClassCard: typeof import('./src/components/cards/PermitClassCard.vue')['default']
    ProcessSteps: typeof import('./src/components/ProcessSteps.vue')['default']
    ProfCard: typeof import('./src/components/cards/ProfCard.vue')['default']
    RolePlayCard: typeof import('./src/components/cards/RolePlayCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RPCard: typeof import('./src/components/cards/RPCard.vue')['default']
    RuleList: typeof import('./src/components/wiki/RuleList.vue')['default']
    SandboxHeader: typeof import('./src/components/sections/SandboxHeader.vue')['default']
    SandboxIntro: typeof import('./src/components/sections/SandboxIntro.vue')['default']
    SandboxNav: typeof import('./src/components/nav/SandboxNav.vue')['default']
    SectionWrapped: typeof import('./src/components/SectionWrapped.vue')['default']
    SyncNav: typeof import('./src/components/nav/SyncNav.vue')['default']
    WikiAlert: typeof import('./src/components/wiki/WikiAlert.vue')['default']
    WikiCallout: typeof import('./src/components/wiki/WikiCallout.vue')['default']
    WikiCard: typeof import('./src/components/wiki/WikiCard.vue')['default']
    WikiHero: typeof import('./src/components/sections/WikiHero.vue')['default']
  }
}
