/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtnCont: typeof import('./src/components/container/BtnCont.vue')['default']
    CardCont: typeof import('./src/components/container/CardCont.vue')['default']
    ListComponent: typeof import('./src/components/ListComponent.vue')['default']
    MasterNav: typeof import('./src/components/navigation/MasterNav.vue')['default']
    PermitClassCard: typeof import('./src/components/cards/PermitClassCard.vue')['default']
    ProcessSteps: typeof import('./src/components/ProcessSteps.vue')['default']
    ProfCard: typeof import('./src/components/cards/ProfCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SandboxNav: typeof import('./src/components/navigation/sandboxNav.vue')['default']
    SectionWrapped: typeof import('./src/components/SectionWrapped.vue')['default']
    SyncNav: typeof import('./src/components/navigation/syncNav.vue')['default']
  }
}
