/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_special/not-found/': RouteRecordInfo<
      '/_special/not-found/',
      '/_special/not-found',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/level': RouteRecordInfo<
      '/level',
      '/level',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/': RouteRecordInfo<
      '/sandbox/',
      '/sandbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/academia/': RouteRecordInfo<
      '/sandbox/academia/',
      '/sandbox/academia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/': RouteRecordInfo<
      '/sandbox/characters/',
      '/sandbox/characters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc': RouteRecordInfo<
      '/sandbox/characters/npc',
      '/sandbox/characters/npc',
      Record<never, never>,
      Record<never, never>,
      | '/sandbox/characters/npc/'
      | '/sandbox/characters/npc/_npc_template/'
      | '/sandbox/characters/npc/_npc_template/pokemon/'
      | '/sandbox/characters/npc/_npc_template/rp-changes/'
      | '/sandbox/characters/npc/karen/'
      | '/sandbox/characters/npc/karen/pokemon/'
      | '/sandbox/characters/npc/karen/rp-changes/'
      | '/sandbox/characters/npc/koga/'
      | '/sandbox/characters/npc/koga/pokemon/'
      | '/sandbox/characters/npc/koga/rp-changes/'
      | '/sandbox/characters/npc/lorelei/'
      | '/sandbox/characters/npc/lorelei/pokemon/'
      | '/sandbox/characters/npc/lorelei/rp-changes/'
      | '/sandbox/characters/npc/will/'
      | '/sandbox/characters/npc/will/pokemon/'
      | '/sandbox/characters/npc/will/rp-changes/'
    >,
    '/sandbox/characters/npc/': RouteRecordInfo<
      '/sandbox/characters/npc/',
      '/sandbox/characters/npc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/_npc_template/': RouteRecordInfo<
      '/sandbox/characters/npc/_npc_template/',
      '/sandbox/characters/npc/_npc_template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/_npc_template/pokemon/': RouteRecordInfo<
      '/sandbox/characters/npc/_npc_template/pokemon/',
      '/sandbox/characters/npc/_npc_template/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/_npc_template/rp-changes/': RouteRecordInfo<
      '/sandbox/characters/npc/_npc_template/rp-changes/',
      '/sandbox/characters/npc/_npc_template/rp-changes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/karen/': RouteRecordInfo<
      '/sandbox/characters/npc/karen/',
      '/sandbox/characters/npc/karen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/karen/pokemon/': RouteRecordInfo<
      '/sandbox/characters/npc/karen/pokemon/',
      '/sandbox/characters/npc/karen/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/karen/rp-changes/': RouteRecordInfo<
      '/sandbox/characters/npc/karen/rp-changes/',
      '/sandbox/characters/npc/karen/rp-changes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/koga/': RouteRecordInfo<
      '/sandbox/characters/npc/koga/',
      '/sandbox/characters/npc/koga',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/koga/pokemon/': RouteRecordInfo<
      '/sandbox/characters/npc/koga/pokemon/',
      '/sandbox/characters/npc/koga/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/koga/rp-changes/': RouteRecordInfo<
      '/sandbox/characters/npc/koga/rp-changes/',
      '/sandbox/characters/npc/koga/rp-changes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/lorelei/': RouteRecordInfo<
      '/sandbox/characters/npc/lorelei/',
      '/sandbox/characters/npc/lorelei',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/lorelei/pokemon/': RouteRecordInfo<
      '/sandbox/characters/npc/lorelei/pokemon/',
      '/sandbox/characters/npc/lorelei/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/lorelei/rp-changes/': RouteRecordInfo<
      '/sandbox/characters/npc/lorelei/rp-changes/',
      '/sandbox/characters/npc/lorelei/rp-changes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/will/': RouteRecordInfo<
      '/sandbox/characters/npc/will/',
      '/sandbox/characters/npc/will',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/will/pokemon/': RouteRecordInfo<
      '/sandbox/characters/npc/will/pokemon/',
      '/sandbox/characters/npc/will/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/npc/will/rp-changes/': RouteRecordInfo<
      '/sandbox/characters/npc/will/rp-changes/',
      '/sandbox/characters/npc/will/rp-changes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc': RouteRecordInfo<
      '/sandbox/characters/oc',
      '/sandbox/characters/oc',
      Record<never, never>,
      Record<never, never>,
      | '/sandbox/characters/oc/'
      | '/sandbox/characters/oc/altair/'
      | '/sandbox/characters/oc/altair/pokemon/'
      | '/sandbox/characters/oc/azumi/'
      | '/sandbox/characters/oc/azumi/pokemon/'
      | '/sandbox/characters/oc/dustin/'
      | '/sandbox/characters/oc/dustin/pokemon/'
      | '/sandbox/characters/oc/esther/'
      | '/sandbox/characters/oc/esther/pokemon/'
      | '/sandbox/characters/oc/maker/'
      | '/sandbox/characters/oc/maker/pokemon/'
      | '/sandbox/characters/oc/montagne/'
      | '/sandbox/characters/oc/montagne/pokemon/'
      | '/sandbox/characters/oc/naka/'
      | '/sandbox/characters/oc/naka/pokemon/'
      | '/sandbox/characters/oc/nyra/'
      | '/sandbox/characters/oc/nyra/pokemon/'
      | '/sandbox/characters/oc/reggie/'
      | '/sandbox/characters/oc/reggie/pokemon/'
    >,
    '/sandbox/characters/oc/': RouteRecordInfo<
      '/sandbox/characters/oc/',
      '/sandbox/characters/oc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/altair/': RouteRecordInfo<
      '/sandbox/characters/oc/altair/',
      '/sandbox/characters/oc/altair',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/altair/pokemon/': RouteRecordInfo<
      '/sandbox/characters/oc/altair/pokemon/',
      '/sandbox/characters/oc/altair/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/azumi/': RouteRecordInfo<
      '/sandbox/characters/oc/azumi/',
      '/sandbox/characters/oc/azumi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/azumi/pokemon/': RouteRecordInfo<
      '/sandbox/characters/oc/azumi/pokemon/',
      '/sandbox/characters/oc/azumi/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/dustin/': RouteRecordInfo<
      '/sandbox/characters/oc/dustin/',
      '/sandbox/characters/oc/dustin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/dustin/pokemon/': RouteRecordInfo<
      '/sandbox/characters/oc/dustin/pokemon/',
      '/sandbox/characters/oc/dustin/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/esther/': RouteRecordInfo<
      '/sandbox/characters/oc/esther/',
      '/sandbox/characters/oc/esther',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/esther/pokemon/': RouteRecordInfo<
      '/sandbox/characters/oc/esther/pokemon/',
      '/sandbox/characters/oc/esther/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/maker/': RouteRecordInfo<
      '/sandbox/characters/oc/maker/',
      '/sandbox/characters/oc/maker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/maker/pokemon/': RouteRecordInfo<
      '/sandbox/characters/oc/maker/pokemon/',
      '/sandbox/characters/oc/maker/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/montagne/': RouteRecordInfo<
      '/sandbox/characters/oc/montagne/',
      '/sandbox/characters/oc/montagne',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/montagne/pokemon/': RouteRecordInfo<
      '/sandbox/characters/oc/montagne/pokemon/',
      '/sandbox/characters/oc/montagne/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/naka/': RouteRecordInfo<
      '/sandbox/characters/oc/naka/',
      '/sandbox/characters/oc/naka',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/naka/pokemon/': RouteRecordInfo<
      '/sandbox/characters/oc/naka/pokemon/',
      '/sandbox/characters/oc/naka/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/nyra/': RouteRecordInfo<
      '/sandbox/characters/oc/nyra/',
      '/sandbox/characters/oc/nyra',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/nyra/pokemon/': RouteRecordInfo<
      '/sandbox/characters/oc/nyra/pokemon/',
      '/sandbox/characters/oc/nyra/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/reggie/': RouteRecordInfo<
      '/sandbox/characters/oc/reggie/',
      '/sandbox/characters/oc/reggie',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/oc/reggie/pokemon/': RouteRecordInfo<
      '/sandbox/characters/oc/reggie/pokemon/',
      '/sandbox/characters/oc/reggie/pokemon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/': RouteRecordInfo<
      '/sandbox/events/',
      '/sandbox/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/balloon-race/': RouteRecordInfo<
      '/sandbox/events/balloon-race/',
      '/sandbox/events/balloon-race',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/balloon-race/2022-08-01/': RouteRecordInfo<
      '/sandbox/events/balloon-race/2022-08-01/',
      '/sandbox/events/balloon-race/2022-08-01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/contest/exeggutor-isle/2022-08-11/': RouteRecordInfo<
      '/sandbox/events/contest/exeggutor-isle/2022-08-11/',
      '/sandbox/events/contest/exeggutor-isle/2022-08-11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/contest/hauoli/2022-08-23/': RouteRecordInfo<
      '/sandbox/events/contest/hauoli/2022-08-23/',
      '/sandbox/events/contest/hauoli/2022-08-23',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/festival/rivers-crown/2022-08-04/': RouteRecordInfo<
      '/sandbox/events/festival/rivers-crown/2022-08-04/',
      '/sandbox/events/festival/rivers-crown/2022-08-04',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/tournament/indigo-conference/2022-12-05/': RouteRecordInfo<
      '/sandbox/events/tournament/indigo-conference/2022-12-05/',
      '/sandbox/events/tournament/indigo-conference/2022-12-05',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/': RouteRecordInfo<
      '/sandbox/orgs/',
      '/sandbox/orgs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/activities-committee/': RouteRecordInfo<
      '/sandbox/orgs/activities-committee/',
      '/sandbox/orgs/activities-committee',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/aether-foundation/': RouteRecordInfo<
      '/sandbox/orgs/aether-foundation/',
      '/sandbox/orgs/aether-foundation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/altru-inc/': RouteRecordInfo<
      '/sandbox/orgs/altru-inc/',
      '/sandbox/orgs/altru-inc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/aqua/': RouteRecordInfo<
      '/sandbox/orgs/aqua/',
      '/sandbox/orgs/aqua',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/athletics-board/': RouteRecordInfo<
      '/sandbox/orgs/athletics-board/',
      '/sandbox/orgs/athletics-board',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/aviation-agency/': RouteRecordInfo<
      '/sandbox/orgs/aviation-agency/',
      '/sandbox/orgs/aviation-agency',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/cipher/': RouteRecordInfo<
      '/sandbox/orgs/cipher/',
      '/sandbox/orgs/cipher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/devon-corp/': RouteRecordInfo<
      '/sandbox/orgs/devon-corp/',
      '/sandbox/orgs/devon-corp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/dim-sun/': RouteRecordInfo<
      '/sandbox/orgs/dim-sun/',
      '/sandbox/orgs/dim-sun',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/flare/': RouteRecordInfo<
      '/sandbox/orgs/flare/',
      '/sandbox/orgs/flare',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/galactic/': RouteRecordInfo<
      '/sandbox/orgs/galactic/',
      '/sandbox/orgs/galactic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inspection-agency/': RouteRecordInfo<
      '/sandbox/orgs/inspection-agency/',
      '/sandbox/orgs/inspection-agency',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inter-pol/': RouteRecordInfo<
      '/sandbox/orgs/inter-pol/',
      '/sandbox/orgs/inter-pol',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inter-pol/AceTrainers/': RouteRecordInfo<
      '/sandbox/orgs/inter-pol/AceTrainers/',
      '/sandbox/orgs/inter-pol/AceTrainers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inter-pol/bounties/': RouteRecordInfo<
      '/sandbox/orgs/inter-pol/bounties/',
      '/sandbox/orgs/inter-pol/bounties',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inter-pol/recruitment/': RouteRecordInfo<
      '/sandbox/orgs/inter-pol/recruitment/',
      '/sandbox/orgs/inter-pol/recruitment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/lysandre-labs/': RouteRecordInfo<
      '/sandbox/orgs/lysandre-labs/',
      '/sandbox/orgs/lysandre-labs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/macro-cosmos/': RouteRecordInfo<
      '/sandbox/orgs/macro-cosmos/',
      '/sandbox/orgs/macro-cosmos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/magma/': RouteRecordInfo<
      '/sandbox/orgs/magma/',
      '/sandbox/orgs/magma',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/maritime-ministry/': RouteRecordInfo<
      '/sandbox/orgs/maritime-ministry/',
      '/sandbox/orgs/maritime-ministry',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/neo-plasma/': RouteRecordInfo<
      '/sandbox/orgs/neo-plasma/',
      '/sandbox/orgs/neo-plasma',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/pinchers/': RouteRecordInfo<
      '/sandbox/orgs/pinchers/',
      '/sandbox/orgs/pinchers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/plasma/': RouteRecordInfo<
      '/sandbox/orgs/plasma/',
      '/sandbox/orgs/plasma',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/poke-association/': RouteRecordInfo<
      '/sandbox/orgs/poke-association/',
      '/sandbox/orgs/poke-association',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/ranger-union/': RouteRecordInfo<
      '/sandbox/orgs/ranger-union/',
      '/sandbox/orgs/ranger-union',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/ranger-union/recruitment/': RouteRecordInfo<
      '/sandbox/orgs/ranger-union/recruitment/',
      '/sandbox/orgs/ranger-union/recruitment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/rocket/': RouteRecordInfo<
      '/sandbox/orgs/rocket/',
      '/sandbox/orgs/rocket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/silph-co/': RouteRecordInfo<
      '/sandbox/orgs/silph-co/',
      '/sandbox/orgs/silph-co',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/transport-tribunal/': RouteRecordInfo<
      '/sandbox/orgs/transport-tribunal/',
      '/sandbox/orgs/transport-tribunal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/': RouteRecordInfo<
      '/sandbox/regions/',
      '/sandbox/regions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/': RouteRecordInfo<
      '/sandbox/regions/indigo/',
      '/sandbox/regions/indigo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/johto/': RouteRecordInfo<
      '/sandbox/regions/indigo/johto/',
      '/sandbox/regions/indigo/johto',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/johto/events/': RouteRecordInfo<
      '/sandbox/regions/indigo/johto/events/',
      '/sandbox/regions/indigo/johto/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/johto/league/': RouteRecordInfo<
      '/sandbox/regions/indigo/johto/league/',
      '/sandbox/regions/indigo/johto/league',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/johto/league/gyms/': RouteRecordInfo<
      '/sandbox/regions/indigo/johto/league/gyms/',
      '/sandbox/regions/indigo/johto/league/gyms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/johto/settlements/': RouteRecordInfo<
      '/sandbox/regions/indigo/johto/settlements/',
      '/sandbox/regions/indigo/johto/settlements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/kanto/': RouteRecordInfo<
      '/sandbox/regions/indigo/kanto/',
      '/sandbox/regions/indigo/kanto',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/kanto/events/': RouteRecordInfo<
      '/sandbox/regions/indigo/kanto/events/',
      '/sandbox/regions/indigo/kanto/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/kanto/league/': RouteRecordInfo<
      '/sandbox/regions/indigo/kanto/league/',
      '/sandbox/regions/indigo/kanto/league',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/kanto/league/gyms/': RouteRecordInfo<
      '/sandbox/regions/indigo/kanto/league/gyms/',
      '/sandbox/regions/indigo/kanto/league/gyms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/kanto/settlements/': RouteRecordInfo<
      '/sandbox/regions/indigo/kanto/settlements/',
      '/sandbox/regions/indigo/kanto/settlements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/league/': RouteRecordInfo<
      '/sandbox/regions/indigo/league/',
      '/sandbox/regions/indigo/league',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/indigo/league/champion-league/': RouteRecordInfo<
      '/sandbox/regions/indigo/league/champion-league/',
      '/sandbox/regions/indigo/league/champion-league',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/rules/': RouteRecordInfo<
      '/sandbox/rules/',
      '/sandbox/rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/setting/': RouteRecordInfo<
      '/sandbox/setting/',
      '/sandbox/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/tech/': RouteRecordInfo<
      '/sandbox/tech/',
      '/sandbox/tech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/todo/': RouteRecordInfo<
      '/sandbox/todo/',
      '/sandbox/todo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/': RouteRecordInfo<
      '/sandbox/trainer-101/',
      '/sandbox/trainer-101',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/ids/': RouteRecordInfo<
      '/sandbox/trainer-101/ids/',
      '/sandbox/trainer-101/ids',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/permits/': RouteRecordInfo<
      '/sandbox/trainer-101/permits/',
      '/sandbox/trainer-101/permits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/permits/aviation/': RouteRecordInfo<
      '/sandbox/trainer-101/permits/aviation/',
      '/sandbox/trainer-101/permits/aviation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/permits/maritime/': RouteRecordInfo<
      '/sandbox/trainer-101/permits/maritime/',
      '/sandbox/trainer-101/permits/maritime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/permits/terrestrial/': RouteRecordInfo<
      '/sandbox/trainer-101/permits/terrestrial/',
      '/sandbox/trainer-101/permits/terrestrial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-paths/': RouteRecordInfo<
      '/sandbox/trainer-paths/',
      '/sandbox/trainer-paths',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/': RouteRecordInfo<
      '/sync/',
      '/sync',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/CalculatorView': RouteRecordInfo<
      '/sync/main/CalculatorView',
      '/sync/main/CalculatorView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/CharacterView': RouteRecordInfo<
      '/sync/main/CharacterView',
      '/sync/main/CharacterView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/FortitudeView': RouteRecordInfo<
      '/sync/main/FortitudeView',
      '/sync/main/FortitudeView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/GymView': RouteRecordInfo<
      '/sync/main/GymView',
      '/sync/main/GymView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/PokeAcademyView': RouteRecordInfo<
      '/sync/main/PokeAcademyView',
      '/sync/main/PokeAcademyView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/PokeJobsView': RouteRecordInfo<
      '/sync/main/PokeJobsView',
      '/sync/main/PokeJobsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/PokeMartView': RouteRecordInfo<
      '/sync/main/PokeMartView',
      '/sync/main/PokeMartView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/SettingView': RouteRecordInfo<
      '/sync/main/SettingView',
      '/sync/main/SettingView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/SwarmsView': RouteRecordInfo<
      '/sync/main/SwarmsView',
      '/sync/main/SwarmsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/SyncEventsView': RouteRecordInfo<
      '/sync/main/SyncEventsView',
      '/sync/main/SyncEventsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/VocationsView': RouteRecordInfo<
      '/sync/main/VocationsView',
      '/sync/main/VocationsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/_special/not-found/index.vue': {
      routes:
        | '/_special/not-found/'
      views:
        | never
    }
    'src/views/level.vue': {
      routes:
        | '/level'
      views:
        | never
    }
    'src/views/sandbox/index.vue': {
      routes:
        | '/sandbox/'
      views:
        | never
    }
    'src/views/sandbox/academia/index.vue': {
      routes:
        | '/sandbox/academia/'
      views:
        | never
    }
    'src/views/sandbox/characters/index.vue': {
      routes:
        | '/sandbox/characters/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc.vue': {
      routes:
        | '/sandbox/characters/npc'
        | '/sandbox/characters/npc/'
        | '/sandbox/characters/npc/_npc_template/'
        | '/sandbox/characters/npc/_npc_template/pokemon/'
        | '/sandbox/characters/npc/_npc_template/rp-changes/'
        | '/sandbox/characters/npc/karen/'
        | '/sandbox/characters/npc/karen/pokemon/'
        | '/sandbox/characters/npc/karen/rp-changes/'
        | '/sandbox/characters/npc/koga/'
        | '/sandbox/characters/npc/koga/pokemon/'
        | '/sandbox/characters/npc/koga/rp-changes/'
        | '/sandbox/characters/npc/lorelei/'
        | '/sandbox/characters/npc/lorelei/pokemon/'
        | '/sandbox/characters/npc/lorelei/rp-changes/'
        | '/sandbox/characters/npc/will/'
        | '/sandbox/characters/npc/will/pokemon/'
        | '/sandbox/characters/npc/will/rp-changes/'
      views:
        | 'default'
    }
    'src/views/sandbox/characters/npc/index.vue': {
      routes:
        | '/sandbox/characters/npc/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/_npc_template/index.vue': {
      routes:
        | '/sandbox/characters/npc/_npc_template/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/_npc_template/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/npc/_npc_template/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/_npc_template/rp-changes/index.vue': {
      routes:
        | '/sandbox/characters/npc/_npc_template/rp-changes/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/karen/index.vue': {
      routes:
        | '/sandbox/characters/npc/karen/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/karen/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/npc/karen/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/karen/rp-changes/index.vue': {
      routes:
        | '/sandbox/characters/npc/karen/rp-changes/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/koga/index.vue': {
      routes:
        | '/sandbox/characters/npc/koga/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/koga/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/npc/koga/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/koga/rp-changes/index.vue': {
      routes:
        | '/sandbox/characters/npc/koga/rp-changes/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/lorelei/index.vue': {
      routes:
        | '/sandbox/characters/npc/lorelei/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/lorelei/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/npc/lorelei/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/lorelei/rp-changes/index.vue': {
      routes:
        | '/sandbox/characters/npc/lorelei/rp-changes/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/will/index.vue': {
      routes:
        | '/sandbox/characters/npc/will/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/will/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/npc/will/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/npc/will/rp-changes/index.vue': {
      routes:
        | '/sandbox/characters/npc/will/rp-changes/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc.vue': {
      routes:
        | '/sandbox/characters/oc'
        | '/sandbox/characters/oc/'
        | '/sandbox/characters/oc/altair/'
        | '/sandbox/characters/oc/altair/pokemon/'
        | '/sandbox/characters/oc/azumi/'
        | '/sandbox/characters/oc/azumi/pokemon/'
        | '/sandbox/characters/oc/dustin/'
        | '/sandbox/characters/oc/dustin/pokemon/'
        | '/sandbox/characters/oc/esther/'
        | '/sandbox/characters/oc/esther/pokemon/'
        | '/sandbox/characters/oc/maker/'
        | '/sandbox/characters/oc/maker/pokemon/'
        | '/sandbox/characters/oc/montagne/'
        | '/sandbox/characters/oc/montagne/pokemon/'
        | '/sandbox/characters/oc/naka/'
        | '/sandbox/characters/oc/naka/pokemon/'
        | '/sandbox/characters/oc/nyra/'
        | '/sandbox/characters/oc/nyra/pokemon/'
        | '/sandbox/characters/oc/reggie/'
        | '/sandbox/characters/oc/reggie/pokemon/'
      views:
        | 'default'
    }
    'src/views/sandbox/characters/oc/index.vue': {
      routes:
        | '/sandbox/characters/oc/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/altair/index.vue': {
      routes:
        | '/sandbox/characters/oc/altair/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/altair/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/oc/altair/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/azumi/index.vue': {
      routes:
        | '/sandbox/characters/oc/azumi/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/azumi/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/oc/azumi/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/dustin/index.vue': {
      routes:
        | '/sandbox/characters/oc/dustin/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/dustin/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/oc/dustin/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/esther/index.vue': {
      routes:
        | '/sandbox/characters/oc/esther/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/esther/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/oc/esther/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/maker/index.vue': {
      routes:
        | '/sandbox/characters/oc/maker/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/maker/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/oc/maker/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/montagne/index.vue': {
      routes:
        | '/sandbox/characters/oc/montagne/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/montagne/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/oc/montagne/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/naka/index.vue': {
      routes:
        | '/sandbox/characters/oc/naka/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/naka/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/oc/naka/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/nyra/index.vue': {
      routes:
        | '/sandbox/characters/oc/nyra/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/nyra/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/oc/nyra/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/reggie/index.vue': {
      routes:
        | '/sandbox/characters/oc/reggie/'
      views:
        | never
    }
    'src/views/sandbox/characters/oc/reggie/pokemon/index.vue': {
      routes:
        | '/sandbox/characters/oc/reggie/pokemon/'
      views:
        | never
    }
    'src/views/sandbox/events/index.vue': {
      routes:
        | '/sandbox/events/'
      views:
        | never
    }
    'src/views/sandbox/events/balloon-race/index.vue': {
      routes:
        | '/sandbox/events/balloon-race/'
      views:
        | never
    }
    'src/views/sandbox/events/balloon-race/2022-08-01/index.vue': {
      routes:
        | '/sandbox/events/balloon-race/2022-08-01/'
      views:
        | never
    }
    'src/views/sandbox/events/contest/exeggutor-isle/2022-08-11/index.vue': {
      routes:
        | '/sandbox/events/contest/exeggutor-isle/2022-08-11/'
      views:
        | never
    }
    'src/views/sandbox/events/contest/hauoli/2022-08-23/index.vue': {
      routes:
        | '/sandbox/events/contest/hauoli/2022-08-23/'
      views:
        | never
    }
    'src/views/sandbox/events/festival/rivers-crown/2022-08-04/index.vue': {
      routes:
        | '/sandbox/events/festival/rivers-crown/2022-08-04/'
      views:
        | never
    }
    'src/views/sandbox/events/tournament/indigo-conference/2022-12-05/index.vue': {
      routes:
        | '/sandbox/events/tournament/indigo-conference/2022-12-05/'
      views:
        | never
    }
    'src/views/sandbox/orgs/index.vue': {
      routes:
        | '/sandbox/orgs/'
      views:
        | never
    }
    'src/views/sandbox/orgs/activities-committee/index.vue': {
      routes:
        | '/sandbox/orgs/activities-committee/'
      views:
        | never
    }
    'src/views/sandbox/orgs/aether-foundation/index.vue': {
      routes:
        | '/sandbox/orgs/aether-foundation/'
      views:
        | never
    }
    'src/views/sandbox/orgs/altru-inc/index.vue': {
      routes:
        | '/sandbox/orgs/altru-inc/'
      views:
        | never
    }
    'src/views/sandbox/orgs/aqua/index.vue': {
      routes:
        | '/sandbox/orgs/aqua/'
      views:
        | never
    }
    'src/views/sandbox/orgs/athletics-board/index.vue': {
      routes:
        | '/sandbox/orgs/athletics-board/'
      views:
        | never
    }
    'src/views/sandbox/orgs/aviation-agency/index.vue': {
      routes:
        | '/sandbox/orgs/aviation-agency/'
      views:
        | never
    }
    'src/views/sandbox/orgs/cipher/index.vue': {
      routes:
        | '/sandbox/orgs/cipher/'
      views:
        | never
    }
    'src/views/sandbox/orgs/devon-corp/index.vue': {
      routes:
        | '/sandbox/orgs/devon-corp/'
      views:
        | never
    }
    'src/views/sandbox/orgs/dim-sun/index.vue': {
      routes:
        | '/sandbox/orgs/dim-sun/'
      views:
        | never
    }
    'src/views/sandbox/orgs/flare/index.vue': {
      routes:
        | '/sandbox/orgs/flare/'
      views:
        | never
    }
    'src/views/sandbox/orgs/galactic/index.vue': {
      routes:
        | '/sandbox/orgs/galactic/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inspection-agency/index.vue': {
      routes:
        | '/sandbox/orgs/inspection-agency/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inter-pol/index.vue': {
      routes:
        | '/sandbox/orgs/inter-pol/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inter-pol/AceTrainers/index.vue': {
      routes:
        | '/sandbox/orgs/inter-pol/AceTrainers/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inter-pol/bounties/index.vue': {
      routes:
        | '/sandbox/orgs/inter-pol/bounties/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inter-pol/recruitment/index.vue': {
      routes:
        | '/sandbox/orgs/inter-pol/recruitment/'
      views:
        | never
    }
    'src/views/sandbox/orgs/lysandre-labs/index.vue': {
      routes:
        | '/sandbox/orgs/lysandre-labs/'
      views:
        | never
    }
    'src/views/sandbox/orgs/macro-cosmos/index.vue': {
      routes:
        | '/sandbox/orgs/macro-cosmos/'
      views:
        | never
    }
    'src/views/sandbox/orgs/magma/index.vue': {
      routes:
        | '/sandbox/orgs/magma/'
      views:
        | never
    }
    'src/views/sandbox/orgs/maritime-ministry/index.vue': {
      routes:
        | '/sandbox/orgs/maritime-ministry/'
      views:
        | never
    }
    'src/views/sandbox/orgs/neo-plasma/index.vue': {
      routes:
        | '/sandbox/orgs/neo-plasma/'
      views:
        | never
    }
    'src/views/sandbox/orgs/pinchers/index.vue': {
      routes:
        | '/sandbox/orgs/pinchers/'
      views:
        | never
    }
    'src/views/sandbox/orgs/plasma/index.vue': {
      routes:
        | '/sandbox/orgs/plasma/'
      views:
        | never
    }
    'src/views/sandbox/orgs/poke-association/index.vue': {
      routes:
        | '/sandbox/orgs/poke-association/'
      views:
        | never
    }
    'src/views/sandbox/orgs/ranger-union/index.vue': {
      routes:
        | '/sandbox/orgs/ranger-union/'
      views:
        | never
    }
    'src/views/sandbox/orgs/ranger-union/recruitment/index.vue': {
      routes:
        | '/sandbox/orgs/ranger-union/recruitment/'
      views:
        | never
    }
    'src/views/sandbox/orgs/rocket/index.vue': {
      routes:
        | '/sandbox/orgs/rocket/'
      views:
        | never
    }
    'src/views/sandbox/orgs/silph-co/index.vue': {
      routes:
        | '/sandbox/orgs/silph-co/'
      views:
        | never
    }
    'src/views/sandbox/orgs/transport-tribunal/index.vue': {
      routes:
        | '/sandbox/orgs/transport-tribunal/'
      views:
        | never
    }
    'src/views/sandbox/regions/index.vue': {
      routes:
        | '/sandbox/regions/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/index.vue': {
      routes:
        | '/sandbox/regions/indigo/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/johto/index.vue': {
      routes:
        | '/sandbox/regions/indigo/johto/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/johto/events/index.vue': {
      routes:
        | '/sandbox/regions/indigo/johto/events/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/johto/league/index.vue': {
      routes:
        | '/sandbox/regions/indigo/johto/league/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/johto/league/gyms/index.vue': {
      routes:
        | '/sandbox/regions/indigo/johto/league/gyms/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/johto/settlements/index.vue': {
      routes:
        | '/sandbox/regions/indigo/johto/settlements/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/kanto/index.vue': {
      routes:
        | '/sandbox/regions/indigo/kanto/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/kanto/events/index.vue': {
      routes:
        | '/sandbox/regions/indigo/kanto/events/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/kanto/league/index.vue': {
      routes:
        | '/sandbox/regions/indigo/kanto/league/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/kanto/league/gyms/index.vue': {
      routes:
        | '/sandbox/regions/indigo/kanto/league/gyms/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/kanto/settlements/index.vue': {
      routes:
        | '/sandbox/regions/indigo/kanto/settlements/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/league/index.vue': {
      routes:
        | '/sandbox/regions/indigo/league/'
      views:
        | never
    }
    'src/views/sandbox/regions/indigo/league/champion-league/index.vue': {
      routes:
        | '/sandbox/regions/indigo/league/champion-league/'
      views:
        | never
    }
    'src/views/sandbox/rules/index.vue': {
      routes:
        | '/sandbox/rules/'
      views:
        | never
    }
    'src/views/sandbox/setting/index.vue': {
      routes:
        | '/sandbox/setting/'
      views:
        | never
    }
    'src/views/sandbox/tech/index.vue': {
      routes:
        | '/sandbox/tech/'
      views:
        | never
    }
    'src/views/sandbox/todo/index.vue': {
      routes:
        | '/sandbox/todo/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/index.vue': {
      routes:
        | '/sandbox/trainer-101/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/ids/index.vue': {
      routes:
        | '/sandbox/trainer-101/ids/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/permits/index.vue': {
      routes:
        | '/sandbox/trainer-101/permits/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/permits/aviation/index.vue': {
      routes:
        | '/sandbox/trainer-101/permits/aviation/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/permits/maritime/index.vue': {
      routes:
        | '/sandbox/trainer-101/permits/maritime/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/permits/terrestrial/index.vue': {
      routes:
        | '/sandbox/trainer-101/permits/terrestrial/'
      views:
        | never
    }
    'src/views/sandbox/trainer-paths/index.vue': {
      routes:
        | '/sandbox/trainer-paths/'
      views:
        | never
    }
    'src/views/sync/index.vue': {
      routes:
        | '/sync/'
      views:
        | never
    }
    'src/views/sync/main/CalculatorView.vue': {
      routes:
        | '/sync/main/CalculatorView'
      views:
        | never
    }
    'src/views/sync/main/CharacterView.vue': {
      routes:
        | '/sync/main/CharacterView'
      views:
        | never
    }
    'src/views/sync/main/FortitudeView.vue': {
      routes:
        | '/sync/main/FortitudeView'
      views:
        | never
    }
    'src/views/sync/main/GymView.vue': {
      routes:
        | '/sync/main/GymView'
      views:
        | never
    }
    'src/views/sync/main/PokeAcademyView.vue': {
      routes:
        | '/sync/main/PokeAcademyView'
      views:
        | never
    }
    'src/views/sync/main/PokeJobsView.vue': {
      routes:
        | '/sync/main/PokeJobsView'
      views:
        | never
    }
    'src/views/sync/main/PokeMartView.vue': {
      routes:
        | '/sync/main/PokeMartView'
      views:
        | never
    }
    'src/views/sync/main/SettingView.vue': {
      routes:
        | '/sync/main/SettingView'
      views:
        | never
    }
    'src/views/sync/main/SwarmsView.vue': {
      routes:
        | '/sync/main/SwarmsView'
      views:
        | never
    }
    'src/views/sync/main/SyncEventsView.vue': {
      routes:
        | '/sync/main/SyncEventsView'
      views:
        | never
    }
    'src/views/sync/main/VocationsView.vue': {
      routes:
        | '/sync/main/VocationsView'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
