/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_special/not-found/': RouteRecordInfo<
      '/_special/not-found/',
      '/_special/not-found',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/level': RouteRecordInfo<
      '/level',
      '/level',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/': RouteRecordInfo<
      '/sandbox/',
      '/sandbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/academia/': RouteRecordInfo<
      '/sandbox/academia/',
      '/sandbox/academia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/': RouteRecordInfo<
      '/sandbox/characters/',
      '/sandbox/characters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/characters/[category]/[id]/[[subpage]]': RouteRecordInfo<
      '/sandbox/characters/[category]/[id]/[[subpage]]',
      '/sandbox/characters/:category/:id/:subpage?',
      { category: ParamValue<true>, id: ParamValue<true>, subpage?: ParamValueZeroOrOne<true> },
      { category: ParamValue<false>, id: ParamValue<false>, subpage?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/sandbox/characters/[redirectCat]': RouteRecordInfo<
      '/sandbox/characters/[redirectCat]',
      '/sandbox/characters/:redirectCat',
      { redirectCat: ParamValue<true> },
      { redirectCat: ParamValue<false> },
      | never
    >,
    '/sandbox/events/': RouteRecordInfo<
      '/sandbox/events/',
      '/sandbox/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/balloon-race/': RouteRecordInfo<
      '/sandbox/events/balloon-race/',
      '/sandbox/events/balloon-race',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/balloon-race/2022-08-01/': RouteRecordInfo<
      '/sandbox/events/balloon-race/2022-08-01/',
      '/sandbox/events/balloon-race/2022-08-01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/contest/exeggutor-isle/2022-08-11/': RouteRecordInfo<
      '/sandbox/events/contest/exeggutor-isle/2022-08-11/',
      '/sandbox/events/contest/exeggutor-isle/2022-08-11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/contest/hauoli/2022-08-23/': RouteRecordInfo<
      '/sandbox/events/contest/hauoli/2022-08-23/',
      '/sandbox/events/contest/hauoli/2022-08-23',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/festival/rivers-crown/2022-08-04/': RouteRecordInfo<
      '/sandbox/events/festival/rivers-crown/2022-08-04/',
      '/sandbox/events/festival/rivers-crown/2022-08-04',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/events/tournament/indigo-conference/2022-12-05/': RouteRecordInfo<
      '/sandbox/events/tournament/indigo-conference/2022-12-05/',
      '/sandbox/events/tournament/indigo-conference/2022-12-05',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/': RouteRecordInfo<
      '/sandbox/orgs/',
      '/sandbox/orgs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/activities-committee/': RouteRecordInfo<
      '/sandbox/orgs/activities-committee/',
      '/sandbox/orgs/activities-committee',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/aether-foundation/': RouteRecordInfo<
      '/sandbox/orgs/aether-foundation/',
      '/sandbox/orgs/aether-foundation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/altru-inc/': RouteRecordInfo<
      '/sandbox/orgs/altru-inc/',
      '/sandbox/orgs/altru-inc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/aqua/': RouteRecordInfo<
      '/sandbox/orgs/aqua/',
      '/sandbox/orgs/aqua',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/athletics-board/': RouteRecordInfo<
      '/sandbox/orgs/athletics-board/',
      '/sandbox/orgs/athletics-board',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/aviation-agency/': RouteRecordInfo<
      '/sandbox/orgs/aviation-agency/',
      '/sandbox/orgs/aviation-agency',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/cipher/': RouteRecordInfo<
      '/sandbox/orgs/cipher/',
      '/sandbox/orgs/cipher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/devon-corp/': RouteRecordInfo<
      '/sandbox/orgs/devon-corp/',
      '/sandbox/orgs/devon-corp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/dim-sun/': RouteRecordInfo<
      '/sandbox/orgs/dim-sun/',
      '/sandbox/orgs/dim-sun',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/flare/': RouteRecordInfo<
      '/sandbox/orgs/flare/',
      '/sandbox/orgs/flare',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/galactic/': RouteRecordInfo<
      '/sandbox/orgs/galactic/',
      '/sandbox/orgs/galactic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inspection-agency/': RouteRecordInfo<
      '/sandbox/orgs/inspection-agency/',
      '/sandbox/orgs/inspection-agency',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inter-pol/': RouteRecordInfo<
      '/sandbox/orgs/inter-pol/',
      '/sandbox/orgs/inter-pol',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inter-pol/AceTrainers/': RouteRecordInfo<
      '/sandbox/orgs/inter-pol/AceTrainers/',
      '/sandbox/orgs/inter-pol/AceTrainers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inter-pol/bounties/': RouteRecordInfo<
      '/sandbox/orgs/inter-pol/bounties/',
      '/sandbox/orgs/inter-pol/bounties',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/inter-pol/recruitment/': RouteRecordInfo<
      '/sandbox/orgs/inter-pol/recruitment/',
      '/sandbox/orgs/inter-pol/recruitment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/lysandre-labs/': RouteRecordInfo<
      '/sandbox/orgs/lysandre-labs/',
      '/sandbox/orgs/lysandre-labs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/macro-cosmos/': RouteRecordInfo<
      '/sandbox/orgs/macro-cosmos/',
      '/sandbox/orgs/macro-cosmos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/magma/': RouteRecordInfo<
      '/sandbox/orgs/magma/',
      '/sandbox/orgs/magma',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/maritime-ministry/': RouteRecordInfo<
      '/sandbox/orgs/maritime-ministry/',
      '/sandbox/orgs/maritime-ministry',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/neo-plasma/': RouteRecordInfo<
      '/sandbox/orgs/neo-plasma/',
      '/sandbox/orgs/neo-plasma',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/pinchers/': RouteRecordInfo<
      '/sandbox/orgs/pinchers/',
      '/sandbox/orgs/pinchers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/plasma/': RouteRecordInfo<
      '/sandbox/orgs/plasma/',
      '/sandbox/orgs/plasma',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/poke-association/': RouteRecordInfo<
      '/sandbox/orgs/poke-association/',
      '/sandbox/orgs/poke-association',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/ranger-union/': RouteRecordInfo<
      '/sandbox/orgs/ranger-union/',
      '/sandbox/orgs/ranger-union',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/ranger-union/recruitment/': RouteRecordInfo<
      '/sandbox/orgs/ranger-union/recruitment/',
      '/sandbox/orgs/ranger-union/recruitment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/rocket/': RouteRecordInfo<
      '/sandbox/orgs/rocket/',
      '/sandbox/orgs/rocket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/silph-co/': RouteRecordInfo<
      '/sandbox/orgs/silph-co/',
      '/sandbox/orgs/silph-co',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/orgs/transport-tribunal/': RouteRecordInfo<
      '/sandbox/orgs/transport-tribunal/',
      '/sandbox/orgs/transport-tribunal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/': RouteRecordInfo<
      '/sandbox/regions/',
      '/sandbox/regions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/regions/[regionId]/': RouteRecordInfo<
      '/sandbox/regions/[regionId]/',
      '/sandbox/regions/:regionId',
      { regionId: ParamValue<true> },
      { regionId: ParamValue<false> },
      | never
    >,
    '/sandbox/regions/[regionId]/[leagueId]/[[circuitId]]': RouteRecordInfo<
      '/sandbox/regions/[regionId]/[leagueId]/[[circuitId]]',
      '/sandbox/regions/:regionId/:leagueId/:circuitId?',
      { regionId: ParamValue<true>, leagueId: ParamValue<true>, circuitId?: ParamValueZeroOrOne<true> },
      { regionId: ParamValue<false>, leagueId: ParamValue<false>, circuitId?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/sandbox/regions/[regionId]/events/': RouteRecordInfo<
      '/sandbox/regions/[regionId]/events/',
      '/sandbox/regions/:regionId/events',
      { regionId: ParamValue<true> },
      { regionId: ParamValue<false> },
      | never
    >,
    '/sandbox/regions/[regionId]/geography/': RouteRecordInfo<
      '/sandbox/regions/[regionId]/geography/',
      '/sandbox/regions/:regionId/geography',
      { regionId: ParamValue<true> },
      { regionId: ParamValue<false> },
      | never
    >,
    '/sandbox/regions/[regionId]/geography/routes/[routeId]': RouteRecordInfo<
      '/sandbox/regions/[regionId]/geography/routes/[routeId]',
      '/sandbox/regions/:regionId/geography/routes/:routeId',
      { regionId: ParamValue<true>, routeId: ParamValue<true> },
      { regionId: ParamValue<false>, routeId: ParamValue<false> },
      | never
    >,
    '/sandbox/regions/[regionId]/geography/settlements/[settlementId]': RouteRecordInfo<
      '/sandbox/regions/[regionId]/geography/settlements/[settlementId]',
      '/sandbox/regions/:regionId/geography/settlements/:settlementId',
      { regionId: ParamValue<true>, settlementId: ParamValue<true> },
      { regionId: ParamValue<false>, settlementId: ParamValue<false> },
      | never
    >,
    '/sandbox/rules/': RouteRecordInfo<
      '/sandbox/rules/',
      '/sandbox/rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/setting/': RouteRecordInfo<
      '/sandbox/setting/',
      '/sandbox/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/tech/': RouteRecordInfo<
      '/sandbox/tech/',
      '/sandbox/tech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/todo/': RouteRecordInfo<
      '/sandbox/todo/',
      '/sandbox/todo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/': RouteRecordInfo<
      '/sandbox/trainer-101/',
      '/sandbox/trainer-101',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/ids/': RouteRecordInfo<
      '/sandbox/trainer-101/ids/',
      '/sandbox/trainer-101/ids',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/permits/': RouteRecordInfo<
      '/sandbox/trainer-101/permits/',
      '/sandbox/trainer-101/permits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/permits/aviation/': RouteRecordInfo<
      '/sandbox/trainer-101/permits/aviation/',
      '/sandbox/trainer-101/permits/aviation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/permits/maritime/': RouteRecordInfo<
      '/sandbox/trainer-101/permits/maritime/',
      '/sandbox/trainer-101/permits/maritime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-101/permits/terrestrial/': RouteRecordInfo<
      '/sandbox/trainer-101/permits/terrestrial/',
      '/sandbox/trainer-101/permits/terrestrial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/trainer-paths/': RouteRecordInfo<
      '/sandbox/trainer-paths/',
      '/sandbox/trainer-paths',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/': RouteRecordInfo<
      '/sync/',
      '/sync',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/CalculatorView': RouteRecordInfo<
      '/sync/main/CalculatorView',
      '/sync/main/CalculatorView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/CharacterView': RouteRecordInfo<
      '/sync/main/CharacterView',
      '/sync/main/CharacterView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/FortitudeView': RouteRecordInfo<
      '/sync/main/FortitudeView',
      '/sync/main/FortitudeView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/GymView': RouteRecordInfo<
      '/sync/main/GymView',
      '/sync/main/GymView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/PokeAcademyView': RouteRecordInfo<
      '/sync/main/PokeAcademyView',
      '/sync/main/PokeAcademyView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/PokeJobsView': RouteRecordInfo<
      '/sync/main/PokeJobsView',
      '/sync/main/PokeJobsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/PokeMartView': RouteRecordInfo<
      '/sync/main/PokeMartView',
      '/sync/main/PokeMartView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/SettingView': RouteRecordInfo<
      '/sync/main/SettingView',
      '/sync/main/SettingView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/SwarmsView': RouteRecordInfo<
      '/sync/main/SwarmsView',
      '/sync/main/SwarmsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/SyncEventsView': RouteRecordInfo<
      '/sync/main/SyncEventsView',
      '/sync/main/SyncEventsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sync/main/VocationsView': RouteRecordInfo<
      '/sync/main/VocationsView',
      '/sync/main/VocationsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/_special/not-found/index.vue': {
      routes:
        | '/_special/not-found/'
      views:
        | never
    }
    'src/views/level.vue': {
      routes:
        | '/level'
      views:
        | never
    }
    'src/views/sandbox/index.vue': {
      routes:
        | '/sandbox/'
      views:
        | never
    }
    'src/views/sandbox/academia/index.vue': {
      routes:
        | '/sandbox/academia/'
      views:
        | never
    }
    'src/views/sandbox/characters/index.vue': {
      routes:
        | '/sandbox/characters/'
      views:
        | never
    }
    'src/views/sandbox/characters/[category]/[id]/[[subpage]].vue': {
      routes:
        | '/sandbox/characters/[category]/[id]/[[subpage]]'
      views:
        | never
    }
    'src/views/sandbox/characters/[redirectCat].vue': {
      routes:
        | '/sandbox/characters/[redirectCat]'
      views:
        | never
    }
    'src/views/sandbox/events/index.vue': {
      routes:
        | '/sandbox/events/'
      views:
        | never
    }
    'src/views/sandbox/events/balloon-race/index.vue': {
      routes:
        | '/sandbox/events/balloon-race/'
      views:
        | never
    }
    'src/views/sandbox/events/balloon-race/2022-08-01/index.vue': {
      routes:
        | '/sandbox/events/balloon-race/2022-08-01/'
      views:
        | never
    }
    'src/views/sandbox/events/contest/exeggutor-isle/2022-08-11/index.vue': {
      routes:
        | '/sandbox/events/contest/exeggutor-isle/2022-08-11/'
      views:
        | never
    }
    'src/views/sandbox/events/contest/hauoli/2022-08-23/index.vue': {
      routes:
        | '/sandbox/events/contest/hauoli/2022-08-23/'
      views:
        | never
    }
    'src/views/sandbox/events/festival/rivers-crown/2022-08-04/index.vue': {
      routes:
        | '/sandbox/events/festival/rivers-crown/2022-08-04/'
      views:
        | never
    }
    'src/views/sandbox/events/tournament/indigo-conference/2022-12-05/index.vue': {
      routes:
        | '/sandbox/events/tournament/indigo-conference/2022-12-05/'
      views:
        | never
    }
    'src/views/sandbox/orgs/index.vue': {
      routes:
        | '/sandbox/orgs/'
      views:
        | never
    }
    'src/views/sandbox/orgs/activities-committee/index.vue': {
      routes:
        | '/sandbox/orgs/activities-committee/'
      views:
        | never
    }
    'src/views/sandbox/orgs/aether-foundation/index.vue': {
      routes:
        | '/sandbox/orgs/aether-foundation/'
      views:
        | never
    }
    'src/views/sandbox/orgs/altru-inc/index.vue': {
      routes:
        | '/sandbox/orgs/altru-inc/'
      views:
        | never
    }
    'src/views/sandbox/orgs/aqua/index.vue': {
      routes:
        | '/sandbox/orgs/aqua/'
      views:
        | never
    }
    'src/views/sandbox/orgs/athletics-board/index.vue': {
      routes:
        | '/sandbox/orgs/athletics-board/'
      views:
        | never
    }
    'src/views/sandbox/orgs/aviation-agency/index.vue': {
      routes:
        | '/sandbox/orgs/aviation-agency/'
      views:
        | never
    }
    'src/views/sandbox/orgs/cipher/index.vue': {
      routes:
        | '/sandbox/orgs/cipher/'
      views:
        | never
    }
    'src/views/sandbox/orgs/devon-corp/index.vue': {
      routes:
        | '/sandbox/orgs/devon-corp/'
      views:
        | never
    }
    'src/views/sandbox/orgs/dim-sun/index.vue': {
      routes:
        | '/sandbox/orgs/dim-sun/'
      views:
        | never
    }
    'src/views/sandbox/orgs/flare/index.vue': {
      routes:
        | '/sandbox/orgs/flare/'
      views:
        | never
    }
    'src/views/sandbox/orgs/galactic/index.vue': {
      routes:
        | '/sandbox/orgs/galactic/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inspection-agency/index.vue': {
      routes:
        | '/sandbox/orgs/inspection-agency/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inter-pol/index.vue': {
      routes:
        | '/sandbox/orgs/inter-pol/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inter-pol/AceTrainers/index.vue': {
      routes:
        | '/sandbox/orgs/inter-pol/AceTrainers/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inter-pol/bounties/index.vue': {
      routes:
        | '/sandbox/orgs/inter-pol/bounties/'
      views:
        | never
    }
    'src/views/sandbox/orgs/inter-pol/recruitment/index.vue': {
      routes:
        | '/sandbox/orgs/inter-pol/recruitment/'
      views:
        | never
    }
    'src/views/sandbox/orgs/lysandre-labs/index.vue': {
      routes:
        | '/sandbox/orgs/lysandre-labs/'
      views:
        | never
    }
    'src/views/sandbox/orgs/macro-cosmos/index.vue': {
      routes:
        | '/sandbox/orgs/macro-cosmos/'
      views:
        | never
    }
    'src/views/sandbox/orgs/magma/index.vue': {
      routes:
        | '/sandbox/orgs/magma/'
      views:
        | never
    }
    'src/views/sandbox/orgs/maritime-ministry/index.vue': {
      routes:
        | '/sandbox/orgs/maritime-ministry/'
      views:
        | never
    }
    'src/views/sandbox/orgs/neo-plasma/index.vue': {
      routes:
        | '/sandbox/orgs/neo-plasma/'
      views:
        | never
    }
    'src/views/sandbox/orgs/pinchers/index.vue': {
      routes:
        | '/sandbox/orgs/pinchers/'
      views:
        | never
    }
    'src/views/sandbox/orgs/plasma/index.vue': {
      routes:
        | '/sandbox/orgs/plasma/'
      views:
        | never
    }
    'src/views/sandbox/orgs/poke-association/index.vue': {
      routes:
        | '/sandbox/orgs/poke-association/'
      views:
        | never
    }
    'src/views/sandbox/orgs/ranger-union/index.vue': {
      routes:
        | '/sandbox/orgs/ranger-union/'
      views:
        | never
    }
    'src/views/sandbox/orgs/ranger-union/recruitment/index.vue': {
      routes:
        | '/sandbox/orgs/ranger-union/recruitment/'
      views:
        | never
    }
    'src/views/sandbox/orgs/rocket/index.vue': {
      routes:
        | '/sandbox/orgs/rocket/'
      views:
        | never
    }
    'src/views/sandbox/orgs/silph-co/index.vue': {
      routes:
        | '/sandbox/orgs/silph-co/'
      views:
        | never
    }
    'src/views/sandbox/orgs/transport-tribunal/index.vue': {
      routes:
        | '/sandbox/orgs/transport-tribunal/'
      views:
        | never
    }
    'src/views/sandbox/regions/index.vue': {
      routes:
        | '/sandbox/regions/'
      views:
        | never
    }
    'src/views/sandbox/regions/[regionId]/index.vue': {
      routes:
        | '/sandbox/regions/[regionId]/'
      views:
        | never
    }
    'src/views/sandbox/regions/[regionId]/[leagueId]/[[circuitId]].vue': {
      routes:
        | '/sandbox/regions/[regionId]/[leagueId]/[[circuitId]]'
      views:
        | never
    }
    'src/views/sandbox/regions/[regionId]/events/index.vue': {
      routes:
        | '/sandbox/regions/[regionId]/events/'
      views:
        | never
    }
    'src/views/sandbox/regions/[regionId]/geography/index.vue': {
      routes:
        | '/sandbox/regions/[regionId]/geography/'
      views:
        | never
    }
    'src/views/sandbox/regions/[regionId]/geography/routes/[routeId].vue': {
      routes:
        | '/sandbox/regions/[regionId]/geography/routes/[routeId]'
      views:
        | never
    }
    'src/views/sandbox/regions/[regionId]/geography/settlements/[settlementId].vue': {
      routes:
        | '/sandbox/regions/[regionId]/geography/settlements/[settlementId]'
      views:
        | never
    }
    'src/views/sandbox/rules/index.vue': {
      routes:
        | '/sandbox/rules/'
      views:
        | never
    }
    'src/views/sandbox/setting/index.vue': {
      routes:
        | '/sandbox/setting/'
      views:
        | never
    }
    'src/views/sandbox/tech/index.vue': {
      routes:
        | '/sandbox/tech/'
      views:
        | never
    }
    'src/views/sandbox/todo/index.vue': {
      routes:
        | '/sandbox/todo/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/index.vue': {
      routes:
        | '/sandbox/trainer-101/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/ids/index.vue': {
      routes:
        | '/sandbox/trainer-101/ids/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/permits/index.vue': {
      routes:
        | '/sandbox/trainer-101/permits/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/permits/aviation/index.vue': {
      routes:
        | '/sandbox/trainer-101/permits/aviation/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/permits/maritime/index.vue': {
      routes:
        | '/sandbox/trainer-101/permits/maritime/'
      views:
        | never
    }
    'src/views/sandbox/trainer-101/permits/terrestrial/index.vue': {
      routes:
        | '/sandbox/trainer-101/permits/terrestrial/'
      views:
        | never
    }
    'src/views/sandbox/trainer-paths/index.vue': {
      routes:
        | '/sandbox/trainer-paths/'
      views:
        | never
    }
    'src/views/sync/index.vue': {
      routes:
        | '/sync/'
      views:
        | never
    }
    'src/views/sync/main/CalculatorView.vue': {
      routes:
        | '/sync/main/CalculatorView'
      views:
        | never
    }
    'src/views/sync/main/CharacterView.vue': {
      routes:
        | '/sync/main/CharacterView'
      views:
        | never
    }
    'src/views/sync/main/FortitudeView.vue': {
      routes:
        | '/sync/main/FortitudeView'
      views:
        | never
    }
    'src/views/sync/main/GymView.vue': {
      routes:
        | '/sync/main/GymView'
      views:
        | never
    }
    'src/views/sync/main/PokeAcademyView.vue': {
      routes:
        | '/sync/main/PokeAcademyView'
      views:
        | never
    }
    'src/views/sync/main/PokeJobsView.vue': {
      routes:
        | '/sync/main/PokeJobsView'
      views:
        | never
    }
    'src/views/sync/main/PokeMartView.vue': {
      routes:
        | '/sync/main/PokeMartView'
      views:
        | never
    }
    'src/views/sync/main/SettingView.vue': {
      routes:
        | '/sync/main/SettingView'
      views:
        | never
    }
    'src/views/sync/main/SwarmsView.vue': {
      routes:
        | '/sync/main/SwarmsView'
      views:
        | never
    }
    'src/views/sync/main/SyncEventsView.vue': {
      routes:
        | '/sync/main/SyncEventsView'
      views:
        | never
    }
    'src/views/sync/main/VocationsView.vue': {
      routes:
        | '/sync/main/VocationsView'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
